name: Build and Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-release:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
          os: [windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Process Version
        id: process_version
        shell: pwsh
        run: |
          $Version = "${{ github.ref_name }}"

          $IsPreRelease = if ($Version -like "*-*") { "true" } else { "false" }
          "IS_PRERELEASE=$IsPreRelease" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8

          $RegexPattern = "\d+\.\d+\.\d+"
          $Match = [regex]::Match($Version, $RegexPattern)
          if ($Match.Success) {
              $CleanVersion = $Match.Value
          } else {
              $CleanVersion = "1.0.0"
          }
          
          "VERSION=$Version" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8
          "CLEAN_VERSION=$CleanVersion" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8

          Write-Host "Program Version: $CleanVersion"
          Write-Host "Is Pre Release: $IsPreRelease"

      - name: Create Dist Folders
        id: dist_folders
        shell: pwsh
        run: |
          $DistDir = "out"
          if (Test-Path $DistDir) { Remove-Item -Recurse -Force $DistDir }
          New-Item -ItemType Directory -Path $DistDir
          New-Item -ItemType Directory -Path $DistDir\dist_files
          New-Item -ItemType Directory -Path $DistDir\windows
          New-Item -ItemType Directory -Path $DistDir\ubuntu

          $AbsDistDir = Resolve-Path -Path $DistDir
          $AbsDistFilesDir = Resolve-Path -Path $DistDir\dist_files
          $AbsDistWindowsDir = Resolve-Path -Path $DistDir\windows
          $AbsDistUbuntuDir = Resolve-Path -Path $DistDir\ubuntu

          "DIST_DIR=$AbsDistDir" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8
          "DIST_FILES_DIR=$AbsDistFilesDir" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8
          "DIST_WINDOWS_DIR=$AbsDistWindowsDir" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8
          "DIST_UBUNTU_DIR=$AbsDistUbuntuDir" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8

      - name: Install Qt
        if: matrix.os == 'windows-latest'
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.8.3'
          target: 'desktop'
          arch: 'win64_msvc2022_64'
          modules: 'qtmultimedia'

      - name: Install NSIS
        if: matrix.os == 'windows-latest'
        uses: repolevedavaj/install-nsis@v1.1.0
        with:
          nsis-version: '3.11'

      # --- BUILD WINDOWS ---
      - name: Build Windows
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: ./.github/scripts/BuildWindows.ps1 -ProjectName "Programa"

      # --- CREATING RELEASE ---
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: "Programa ${{ github.ref_name }}"
          files: |
            ${{ env.DIST_FILES_DIR }}/*
          body_path: dist/changes-v${{ env.CLEAN_VERSION }}.md
          prerelease: ${{ env.IS_PRERELEASE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
