name: Build and Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-release:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
          os: [windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Process Version
        id: process_version
        shell: pwsh
        run: |
          $Version = "${{ github.ref_name }}"

          $IsPreRelease = if ($Version -like "*-*") { "true" } else { "false" }
          "IS_PRERELEASE=$IsPreRelease" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8

          $RegexPattern = "\d+\.\d+\.\d+"
          $Match = [regex]::Match($Version, $RegexPattern)
          if ($Match.Success) {
              $CleanVersion = $Match.Value
          } else {
              $CleanVersion = "1.0.0"
          }
          
          "CLEAN_VERSION=$CleanVersion" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8

          Write-Host "Program Version: ${{ env.CLEAN_VERSION }}"
          Write-Host "Pre Release: ${{ env.IS_PRERELEASE }}"

      - name: Install Qt
        if: matrix.os == 'windows-latest'
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.8.3'
          target: 'desktop'
          arch: 'win64_msvc2022_64'
          modules: 'qtmultimedia'

      - name: Install NSIS
        if: matrix.os == 'windows-latest'
        uses: repolevedavaj/install-nsis@v1.1.0
        with:
          nsis-version: '3.11'

      # --- BUILD WINDOWS ---
      - name: Build Windows
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: ./.github/scripts/BuildWindows.ps1 -ProjectName "Programa" -Version "${{ github.ref_name }}"

      # --- CREATING RELEASE ---
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: "Programa ${{ github.ref_name }}"
          files: |
            Programa-${{ github.ref_name }}-Portable-Windows-x86_64.zip
            Programa-${{ github.ref_name }}-Installer-Windows-x86_64.exe
          body_path: dist/changes-v${{ env.CLEAN_VERSION }}.md
          prerelease: ${{ env.IS_PRERELEASE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
